name = "honeymoon-ubud-cloudflare"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[env.production]
name = "honeymoon-ubud-cloudflare-prod"

[env.preview]
name = "honeymoon-ubud-cloudflare-preview"

[env.production.vars]
ENVIRONMENT = "production"

[env.preview.vars]
ENVIRONMENT = "preview"
